### ISSUE TITLE
Don't works in 0.8.6

### ISSUE THREAD

**Issue by Varkal** [EvanesceExotica/Journal-To-Canvas-Slideshow#19]
Hi ! 

I've upgraded my Foundry server to 0.8.6. 
I'm aware the module.json doesn't claim it's compatible with this foundry version. 

And obviously, it's not :-) 

At the loading of the game I got this error in the console : 

```
foundry.js:197 TypeError: Cannot read property 'parentNode' of undefined
    at applySceneHeaderButtons (ClickImageInJournal.js:595)
    at ClickImageInJournal.js:848
    at Function._call (foundry.js:194)
    at Function.call (foundry.js:179)
    at CompactJournalEntryDisplay._render (foundry.js:2096)
    at async CompactJournalEntryDisplay._render (foundry.js:2728)
    at async CompactJournalEntryDisplay._render (foundry.js:25348)
```

Click on the "Create or Show Display Scene" throw : 

```
ClickImageInJournal.js:436 Uncaught (in promise) TypeError: scenes is not iterable
    at DisplaySceneFound (ClickImageInJournal.js:436)
    at HTMLButtonElement.GenerateDisplayScene (ClickImageInJournal.js:341)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
```
Open any journal entry throw 

```
foundry.js:197 TypeError: journalEntries.forEach is not a function
    at FindDisplayJournal (ClickImageInJournal.js:63)
    at ClickImageInJournal.js:852
    at Function._call (foundry.js:194)
    at Function.call (foundry.js:179)
    at s._render (foundry.js:2096)
    at async s._render (foundry.js:2728)
    at async s._render (foundry.js:25348)
```

And click on picture throw : 

```
ClickImageInJournal.js:436 Uncaught (in promise) TypeError: scenes is not iterable
    at DisplaySceneFound (ClickImageInJournal.js:436)
    at displayImageInScene (ClickImageInJournal.js:219)
    at HTMLImageElement.determineLocation (ClickImageInJournal.js:476)
```

I hope that will help you if you plan to make this module compatible with the next version of foundry :-) 

If I free me some time this week maybe i can try to make you a PR for this ?

**Comment by EvanesceExotica** [comment]
Hey there! No worries -- I definitely intend to make this module compatible
with the 8.6 version of Foundry. :) I've been working on it and I seem to
have got the features all working with only a few minor tweaks so far, but
want to do some more testing to make sure it's solid, so hopefully I should
be able to get it out sometime this week. ^ ^

Thanks for your patience!

**Comment by EvanesceExotica** [comment]
Ah, darn, okay! Let me do some more testing and see if I can figure out what's up.

**Comment by DarKDinDoN** [comment]
@EvanesceExotica it seems that you are relying on another module to share an image

![image](https://user-images.githubusercontent.com/1687854/123471200-b678b580-d5f5-11eb-92d7-4b4a26a50409.png)

**Comment by DarKDinDoN** [comment]
Fixed with you own package name: `journal-to-canvas-slideshow`
And adding `"socket": "true",` to module.js

**Comment by DarKDinDoN** [comment]
@EvanesceExotica attempt to fix some errors: https://github.com/EvanesceExotica/Journal-To-Canvas-Slideshow/pull/21

Couldn't reproduce all errors.
But I believe those are fixed:
- Can't share poput window with players
- Cannot read property 'parentNode' of undefined
